#!/bin/bash

#$ -S /bin/bash

#$ -o /work/$USER/$JOB_NAME-$JOB_ID.log
#$ -j y

[[ $1 = "--help" || $1 = "-h" ]] && {
  echo "usage: <submit-command> [submit-args] $0 query database [blast-arguments]"
  exit 0
}

source /global/submit-scripts/util.sh
source /etc/profile.d/000-modules.sh
module load ncbi-blast

INPUT=$1    ; shift
BLAST_DB=$1 ; shift

OUTPUT=$OUTPUT_DIR/result

${TRACE:+tracer} tblastn -query $INPUT -num_threads ${NSLOTS:-1} -db $BLAST_DB "$@" -out $OUTPUT
